fix for armhf buildkit docker
- in Dockerfile.multi-arch, duplicate release phase with explicit arch
  for alpine image. Otherwise, there is a "no match for platform", since the
  alpine:3.9 image doesn't have the armhf annotated

e.g.
error: failed to solve: rpc error: code = Unknown desc = no match for platform in manifest sha256:e58dd3affe1e3530f39b4afc4512feff605b2b010a2d4bae1c9754b646f0c23a: not found

Signed-off-by: David Crook <david.crook@gmail.com>